@extends('layouts.app')
@section('content')
<div class="w-100 d-flex ">@include('sections.setting-sidebar')
<x-setting-card><x-slot name="header"><div class="s-b-n-header"><h2 class="mb-0 p-20 f-21 font-weight-normal border-bottom-grey">Installation #{{ $installation->id }}</h2></div></x-slot>
<div class="p-4">
<div class="row mb-4"><div class="col-md-4"><div class="card border"><div class="card-body"><div class="small text-muted">Module</div><div class="h4">{{ $installation->module_name }}</div></div></div></div><div class="col-md-4"><div class="card border"><div class="card-body"><div class="small text-muted">Status</div><div class="h4">{{ $installation->status }}</div></div></div></div><div class="col-md-4"><div class="card border"><div class="card-body"><div class="small text-muted">Rollback</div><div class="h4">{{ $installation->can_rollback ? 'Available' : 'No' }}</div></div></div></div></div>
<div class="row"><div class="col-md-6 mb-4"><div class="card border h-100"><div class="card-header">Metrics</div><div class="card-body"><pre class="mb-0" style="white-space:pre-wrap">{{ json_encode($metrics, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div></div></div><div class="col-md-6 mb-4"><div class="card border h-100"><div class="card-header">Manifest / Validation</div><div class="card-body"><pre class="mb-0" style="white-space:pre-wrap">{{ json_encode(['manifest'=>$installation->manifest_data,'validation'=>$installation->validation_results,'repairs'=>$installation->repair_results], JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div></div></div></div>
<div class="row"><div class="col-md-6 mb-4"><div class="card border h-100"><div class="card-header">Automated Tests</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Category</th><th>Test</th><th>Result</th></tr></thead><tbody>@forelse($tests as $test)<tr><td>{{ $test->test_category }}</td><td>{{ $test->test_name }}</td><td>{{ $test->success ? 'Pass' : 'Fail' }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No test results recorded.</td></tr>@endforelse</tbody></table></div></div></div></div><div class="col-md-6 mb-4"><div class="card border h-100"><div class="card-header">Recent Logs</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Time</th><th>Event</th><th>Level</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ optional($log->logged_at)->toDateTimeString() }}</td><td>{{ $log->event_type }}</td><td>{{ $log->level }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No logs recorded.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
</div></x-setting-card></div>
@endsection
